### ISSUE TITLE
“afterwards” and “towards” are the norm within 🇬🇧 English

### ISSUE THREAD

**Issue by handcoding** [kemitchell/wordy-words#7]
Just as a heads-up, [“afterwards” and “towards” are the norm within British English](http://www.lawprose.org/lawprose-lesson-200-which-is-standard-toward-or-towards/). So while that’s not to say that I wouldn’t make those swaps if I were editing a document in American English, it might be iffy to present those as universal substitutions that apply to all writing.

**Comment by kemitchell** [comment]
@handcoding: Thanks! I wasn't aware of that usage difference, but I don't think either @anseljh or I particularly want to address a British as well as an American version of this list, being rather American ourselves. If you've need of a British or more "universal" English list, by all means put one together and let us know. The starting point here is [CC0](https://github.com/kemitchell/wordy-words/blob/df4472205de6d81408d5153a9319e5c679dd9004/package.json#L12)-licensed.

**Comment by handcoding** [comment]
@kemitchell Just to toss out an idea, what if you were to have two JSON objects—one for the many substitutions that work in all dialects and one for the substitutions that are specific to American English? That way, for someone who were using those JSON objects to automate those substitutions, they could quite easily feed their function either both JSON objects (if they were American) or one JSON object (if they were outside the US).

And for what it’s worth, I’m an American myself. But as a copy editor, I occasionally have clients from outside the US and they typically ask me to edit their documents using the norms of their local dialect.

**Comment by kemitchell** [comment]
@handcoding: I agree that might be valuable, but I'm afraid Ansel and I aren't the ones to tackle it. We haven't much knowledge in that department, nor have we needs to acquire it at the moment.

As open-source folk go, Ansel and I are a bit old school.  (Okay, Ansel's pretty hip, but he's guilty by association.)  We seem less and less "with it" as days go by---especially here on GitHub---but there are a few tenets of the old coder code that we cling fast to.  Minimizing project scope is the only long-term-viable form of self defense.  If you need it, and it hasn't been done, it's on you!
